title = 'Maxime Sahuc'
baseURL = 'https://maximesahuc.github.io/'

languageCode = 'en-us'
copyright = "Maxime Sahuc © {year}"

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
theme = "auto"
showThemeNotice = false
showPostsSummary = true


# Navigation
[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 2
  
  [[menu.main]]
    identifier = "tags"
    name = "tags"
    title = "tags"
    url = "/tags"
    weight = 3

  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "GitHub"
    url = "https://github.com/MaximeSahuc"
    weight = 4